certificateAuthorities:
  ord-ca.fabric:
    caName: ca
    registrar:
      enrollId: enroll
      enrollSecret: enrollpw
    tlsCACerts:
      pem:
      - |
        -----BEGIN CERTIFICATE-----
        MIICSjCCAfGgAwIBAgIRAOuZoWHhl7A82yhlRQhrGmQwCgYIKoZIzj0EAwIwUjET
        MBEGA1UEBhMKQ2FsaWZvcm5pYTEJMAcGA1UEBxMAMQkwBwYDVQQJEwAxFDASBgNV
        BAoTC0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZGYWJyaWMwHhcNMjIxMDIxMTEzNDIw
        WhcNMzIxMDIyMTEzNDIwWjBSMRMwEQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQH
        EwAxCTAHBgNVBAkTADEUMBIGA1UEChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZh
        YnJpYzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABANBEu8d25XRc3F9PURPVos5
        6IGRktHQ48F1bLkjQlt1FPM36/8gK97wYN+p4ge58As9aoBv+gFG3qkwXd8yLfqj
        gacwgaQwDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
        BQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCC4iQQ3siddL7mt/R5E6Rx0
        2VOA+gGPwB9l7eHBxpaiITA3BgNVHREEMDAugglsb2NhbGhvc3SCBm9yZC1jYYIN
        b3JkLWNhLmZhYnJpY4cEfwAAAYcEsoA+TzAKBggqhkjOPQQDAgNHADBEAiAKi0m2
        qAAR62LN4sw2gGGEY0aj7TzhAD7w8Hq2e6UttwIgP/GNp73U+4XYXqtTa2H7ibgu
        4FzK1KTTO9za4vHhwG0=
        -----END CERTIFICATE-----
    url: https://178.128.62.79:31588
  org1-ca.fabric:
    caName: ca
    registrar:
      enrollId: enroll
      enrollSecret: enrollpw
    tlsCACerts:
      pem:
      - |
        -----BEGIN CERTIFICATE-----
        MIICSzCCAfKgAwIBAgIQbQYpBZLA33K/IOCVJweBYTAKBggqhkjOPQQDAjBSMRMw
        EQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQHEwAxCTAHBgNVBAkTADEUMBIGA1UE
        ChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZhYnJpYzAeFw0yMjEwMjExMTMzMTda
        Fw0zMjEwMjIxMTMzMTdaMFIxEzARBgNVBAYTCkNhbGlmb3JuaWExCTAHBgNVBAcT
        ADEJMAcGA1UECRMAMRQwEgYDVQQKEwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFi
        cmljMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAERIKbWQcpOXgIsFcaNm/8VDBg
        0JpcnyJDqcdGjqIsVyDPs9xeYwQxvcKlWjH0IEYT4uA/+iJEhZzh/PBq9tXJ2KOB
        qTCBpjAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUF
        BwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEIMvlzNBUKOn8fQOmASRgfq6n
        tB3uUK+5g6eJWLU5mJBeMDkGA1UdEQQyMDCCCWxvY2FsaG9zdIIHb3JnMS1jYYIO
        b3JnMS1jYS5mYWJyaWOHBH8AAAGHBLKAPk8wCgYIKoZIzj0EAwIDRwAwRAIgCWzv
        hv7g91mgGRxrv7VluSPqZmW8VyzjbTL79Nak00kCIGnzkpaXlmRewlz0hBkeLScA
        j/ID91fUgkz3jS9Y6VK/
        -----END CERTIFICATE-----
    url: https://178.128.62.79:31656
  org2-ca.fabric:
    caName: ca
    registrar:
      enrollId: enroll
      enrollSecret: enrollpw
    tlsCACerts:
      pem:
      - |
        -----BEGIN CERTIFICATE-----
        MIICTDCCAfKgAwIBAgIQUXlQmhtLlHYHAuc0Z4LDpDAKBggqhkjOPQQDAjBSMRMw
        EQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQHEwAxCTAHBgNVBAkTADEUMBIGA1UE
        ChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZhYnJpYzAeFw0yMjEwMjExMTMzNDda
        Fw0zMjEwMjIxMTMzNDdaMFIxEzARBgNVBAYTCkNhbGlmb3JuaWExCTAHBgNVBAcT
        ADEJMAcGA1UECRMAMRQwEgYDVQQKEwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFi
        cmljMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEmrd4quL+BA6spkxMs7u1ribE
        jCklldn7drBrvFHeBf0fnpcs5EBm5J7zpPfIro9riAU6cqzOHpixkvRffTWVn6OB
        qTCBpjAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUF
        BwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEIBa7V/j/SxUC1WoL4EHESuzh
        +NfBQtjJ8ZFoVjtUbqJxMDkGA1UdEQQyMDCCCWxvY2FsaG9zdIIHb3JnMi1jYYIO
        b3JnMi1jYS5mYWJyaWOHBH8AAAGHBLKAPk8wCgYIKoZIzj0EAwIDSAAwRQIgdBCW
        RewqlV8eU33Hcn6CCj/uBo8/U68oIhhXIAuA9IACIQCs7xIIwYwb5ohiCSUV2OhV
        CFXJbN7/kyfRdf5YH5utlw==
        -----END CERTIFICATE-----
    url: https://178.128.62.79:30297
channels:
  mychannel:
    orderers:
    - ord-node1.fabric
    peers:
      org1-peer1.fabric:
        chaincodeQuery: true
        discover: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      org2-peer1.fabric:
        chaincodeQuery: true
        discover: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      org2-peer2.fabric:
        chaincodeQuery: true
        discover: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
client:
  organization: <no value>
name: hlf-network
orderers:
  ord-node1.fabric:
    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeugAwIBAgIQLJYP3Y4RfQJKpbZmOJ2FKjAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yMjEwMjExMTM0MjBaFw0zMjEwMjIxMTM0MjBaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEDyDn4cpV/dAucPE6
        0hVP0O/+h7CjM/dWtLqjUYDoHiz7JxDOMRUQRRXDDZMmloW5uuhEiEYcA1OHCPDi
        Latir6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCB8LNLfUfLty0RhS5Jc
        Skmc/rZdH0hMSMkpxJsNTu5v+jAKBggqhkjOPQQDAgNJADBGAiEAjHIZOWbraLiM
        JI7pVU0dBVFVOZOyCOyWqlVtwWwHNQUCIQCp4ET/x7UkuwBTx7ekFXV3urrpsR04
        TkpYX4e8EKEBqw==
        -----END CERTIFICATE-----
    url: grpcs://178.128.62.79:30259
organizations:
  OrdererMSP:
    cryptoPath: /tmp/cryptopath
    mspid: OrdererMSP
    orderers:
    - ord-node1.fabric
    peers: []
    users: {}
  Org1MSP:
    cryptoPath: /tmp/cryptopath
    mspid: Org1MSP
    orderers: []
    peers:
    - org1-peer1.fabric
    users:
      admin:
        cert:
          pem: |
            -----BEGIN CERTIFICATE-----
            MIICUjCCAfmgAwIBAgIUAYmwJ3OM3kQqJEdS/Z8tvWXw1BwwCgYIKoZIzj0EAwIw
            ajELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
            YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEL
            MAkGA1UEAxMCY2EwHhcNMjIxMDIyMTIyMDAwWhcNMjMxMDIyMTIyNTAwWjAgMQ4w
            DAYDVQQLEwVhZG1pbjEOMAwGA1UEAxMFYWRtaW4wWTATBgcqhkjOPQIBBggqhkjO
            PQMBBwNCAASk68OkshOwbph60RhGUS9w+9by4ACbC7Sbq0qIENVrmio6wCWLadu9
            V/a0zYpFN7E3cX/+6NnKGgdQ8FPMPWRZo4HGMIHDMA4GA1UdDwEB/wQEAwIHgDAM
            BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBRCe+QwwZ/ndeGK2dZx0GxxlQ5OOjArBgNV
            HSMEJDAigCAxFUsKJZ2PO/AAVZt584XzDMeeXgeLlsdsf1fHbJc0fTBXBggqAwQF
            BgcIAQRLeyJhdHRycyI6eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1l
            bnRJRCI6ImFkbWluIiwiaGYuVHlwZSI6ImFkbWluIn19MAoGCCqGSM49BAMCA0cA
            MEQCICQWpgTWxq7F8Z7yU8YwTTPxNE1zJ/g8Uvu3R0UcKKnUAiBtIEO4A1Jg7v3S
            IifxWc48+qXIJRhDYn8ds9XGceaJOg==
            -----END CERTIFICATE-----
        key:
          pem: |
            -----BEGIN PRIVATE KEY-----
            MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgw+ozD8U1hWpfbwVT
            OCAW/6utMxn8iFlqlXF9Uf7KEoChRANCAASk68OkshOwbph60RhGUS9w+9by4ACb
            C7Sbq0qIENVrmio6wCWLadu9V/a0zYpFN7E3cX/+6NnKGgdQ8FPMPWRZ
            -----END PRIVATE KEY-----
      dana:
        cert:
          pem: |
            -----BEGIN CERTIFICATE-----
            MIICUjCCAfmgAwIBAgIUAYmwJ3OM3kQqJEdS/Z8tvWXw1BwwCgYIKoZIzj0EAwIw
            ajELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
            YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEL
            MAkGA1UEAxMCY2EwHhcNMjIxMDIyMTIyMDAwWhcNMjMxMDIyMTIyNTAwWjAgMQ4w
            DAYDVQQLEwVhZG1pbjEOMAwGA1UEAxMFYWRtaW4wWTATBgcqhkjOPQIBBggqhkjO
            PQMBBwNCAASk68OkshOwbph60RhGUS9w+9by4ACbC7Sbq0qIENVrmio6wCWLadu9
            V/a0zYpFN7E3cX/+6NnKGgdQ8FPMPWRZo4HGMIHDMA4GA1UdDwEB/wQEAwIHgDAM
            BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBRCe+QwwZ/ndeGK2dZx0GxxlQ5OOjArBgNV
            HSMEJDAigCAxFUsKJZ2PO/AAVZt584XzDMeeXgeLlsdsf1fHbJc0fTBXBggqAwQF
            BgcIAQRLeyJhdHRycyI6eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1l
            bnRJRCI6ImFkbWluIiwiaGYuVHlwZSI6ImFkbWluIn19MAoGCCqGSM49BAMCA0cA
            MEQCICQWpgTWxq7F8Z7yU8YwTTPxNE1zJ/g8Uvu3R0UcKKnUAiBtIEO4A1Jg7v3S
            IifxWc48+qXIJRhDYn8ds9XGceaJOg==
            -----END CERTIFICATE-----
        key:
          pem: |
            -----BEGIN PRIVATE KEY-----
            MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgw+ozD8U1hWpfbwVT
            OCAW/6utMxn8iFlqlXF9Uf7KEoChRANCAASk68OkshOwbph60RhGUS9w+9by4ACb
            C7Sbq0qIENVrmio6wCWLadu9V/a0zYpFN7E3cX/+6NnKGgdQ8FPMPWRZ
            -----END PRIVATE KEY-----
  Org2MSP:
    cryptoPath: /tmp/cryptopath
    mspid: Org2MSP
    orderers: []
    peers:
    - org2-peer1.fabric
    - org2-peer2.fabric
    users:
      admin:
        cert:
          pem: |
            -----BEGIN CERTIFICATE-----
            MIICUjCCAfmgAwIBAgIUGKr3lxBH1l1hCyV0lUFTfhAFDsAwCgYIKoZIzj0EAwIw
            ajELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
            YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEL
            MAkGA1UEAxMCY2EwHhcNMjIxMDIyMTIyMDAwWhcNMjMxMDIyMTIyNTAwWjAgMQ4w
            DAYDVQQLEwVhZG1pbjEOMAwGA1UEAxMFYWRtaW4wWTATBgcqhkjOPQIBBggqhkjO
            PQMBBwNCAASRAhcLcE3D7hLatt2mBgAbBSQ8GMzvouHDgsQnRCjopFxJBPE8iMm1
            fWW0ShOHDKg4ltsSPhoXLueitgQiJ5Y3o4HGMIHDMA4GA1UdDwEB/wQEAwIHgDAM
            BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBSk51MuKKuhdTZC6qwcKaUc9mMi3zArBgNV
            HSMEJDAigCDczFiVkymhr05a5aCMsn6WGZo2g8AoSZ2gVv7cYDCN0jBXBggqAwQF
            BgcIAQRLeyJhdHRycyI6eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1l
            bnRJRCI6ImFkbWluIiwiaGYuVHlwZSI6ImFkbWluIn19MAoGCCqGSM49BAMCA0cA
            MEQCIDYJMIk56vvkomZ38LwPYF9SZi1eMU71FzQ9Va8jr4SDAiAhySYJ72hp/OsJ
            Dy07IiUT1HJw//GM5bxoHoPvhVZ1fw==
            -----END CERTIFICATE-----
        key:
          pem: |
            -----BEGIN PRIVATE KEY-----
            MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgXBxQJaqfUY819G2O
            vXu9fm59K69V+1HDAMwVmPWOgIuhRANCAASRAhcLcE3D7hLatt2mBgAbBSQ8GMzv
            ouHDgsQnRCjopFxJBPE8iMm1fWW0ShOHDKg4ltsSPhoXLueitgQiJ5Y3
            -----END PRIVATE KEY-----
peers:
  org1-peer1.fabric:
    grpcOptions:
      allow-insecure: false
      hostnameOverride: ""
      ssl-target-name-override: ""
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICQzCCAeqgAwIBAgIPX+DEBTqNKenNu65lecObMAoGCCqGSM49BAMCMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMB4XDTIyMTAyMTExMzMxN1oXDTMyMTAyMjExMzMxN1owbTELMAkG
        A1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGljYW50ZTEZ
        MBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEOMAwGA1UE
        AxMFdGxzY2EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ1Uc2QEAtJHAgVMUGw
        ojptReBpHuBtsvMjBn3YuAkhjdbAfsb/w88wjKB+TW8pQDDSk+HAKtEwWoml8x1u
        KIVFo20wazAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsG
        AQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEIJogzaykrKwW78EsbEdH
        4cCBSKi3mGAYspiPsviwzvMNMAoGCCqGSM49BAMCA0cAMEQCIAN74XafMOBUsNJM
        Irfx1RnUm2s0sAxclLn0GgbtTWcaAiAg0BxNegj+CR1UIywvZoCnKxdnIa5DWb3u
        Hlw6fd5iXQ==
        -----END CERTIFICATE-----
    url: grpcs://178.128.62.79:30519
  org2-peer1.fabric:
    grpcOptions:
      allow-insecure: false
      hostnameOverride: ""
      ssl-target-name-override: ""
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRDCCAeugAwIBAgIQMT4H9SGsqbbTa2429+9nxzAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yMjEwMjExMTMzNDdaFw0zMjEwMjIxMTMzNDdaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKzwjvjtPWktj/q8j
        +8ZrIq02QVKdmxCBhxlUrCPRbU95ZPWI9LnMbyd8cwzSTVdeBVOWmdk+PegQx4RB
        5M9s3aNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCC2tYqFwjkr0y/gFIG7
        82nOQDVxr/jKfQV8waRLx9g2ezAKBggqhkjOPQQDAgNHADBEAiBGDuhVb0Q9tKBK
        F5FfvN8dBJo1kSMT0fANQj4Y+M4lmAIgdqWqsUDNskNZt+hNjwvYSx1nxnKsPlfi
        pQug7RoME3w=
        -----END CERTIFICATE-----
    url: grpcs://178.128.62.79:31927
  org2-peer2.fabric:
    grpcOptions:
      allow-insecure: false
      hostnameOverride: ""
      ssl-target-name-override: ""
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRDCCAeugAwIBAgIQMT4H9SGsqbbTa2429+9nxzAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yMjEwMjExMTMzNDdaFw0zMjEwMjIxMTMzNDdaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKzwjvjtPWktj/q8j
        +8ZrIq02QVKdmxCBhxlUrCPRbU95ZPWI9LnMbyd8cwzSTVdeBVOWmdk+PegQx4RB
        5M9s3aNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCC2tYqFwjkr0y/gFIG7
        82nOQDVxr/jKfQV8waRLx9g2ezAKBggqhkjOPQQDAgNHADBEAiBGDuhVb0Q9tKBK
        F5FfvN8dBJo1kSMT0fANQj4Y+M4lmAIgdqWqsUDNskNZt+hNjwvYSx1nxnKsPlfi
        pQug7RoME3w=
        -----END CERTIFICATE-----
    url: grpcs://178.128.62.79:30672
version: 1.0.0
